# Generated by Django 4.1.3 on 2022-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_user_date_joined_user_first_name_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
