# Generated by Django 4.1.3 on 2022-11-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_user_date_joined_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(db_column='userId', primary_key=True, serialize=False),
        ),
    ]
