# Generated by Django 4.1.3 on 2022-11-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_user_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalmadebyuser',
            options={'managed': True},
        ),
    ]
